"""
Generic handoff maker — all skill handoff types in one script (GPTS).
Takes a JSON payload with handoff type and fields, writes the markdown file.
Designed for fire-and-forget via `run_in_background: true`.

Also handles self-evolution check (formerly a separate script + gate hook).
When "self_evolution" is present in the JSON, the script triages them inline:
  - Empty list → no issues, routing proceeds (status cleared)
  - Non-empty list → triage menu on stderr, status pending

Usage (flags only; --help prints this contract as JSON):
  $UB make-handoff --json - <<'HANDOFF'
  {"type": "bruce", "ticket_key": "LOC-0076", "fields": {...}}
  HANDOFF

JSON payload keys:
  "base_dir": base directory (optional — defaults to the self-located base)
  "type": handoff type (required)
  "ticket_key": ticket key (required; "STORY/AC2" form allowed for dupin types)
  "self_evolution": list of user corrections (optional)
  "fields": type-specific fields (or flat top-level keys, which are promoted)

Handoff types and their output paths:
  oracle          → handoffs/oracle/Oracle-<key>.md
  dupin           → handoffs/dupin/Dupin-<key>.md
  phase-state     → handoffs/dupin/PhaseState-<key>.md
  alfred          → handoffs/alfred/Alfred-<key>.md
  alfred-notes    → handoffs/alfred/Alfred-<key>-notes.md
  damian          → handoffs/damian/Damian-<key>.md
  damian-case     → handoffs/damian/Damian-<key>-case.md
  bruce           → handoffs/bruce/Bruce-<key>.md (QA)
  bruce-case      → handoffs/bruce/Bruce-<key>-case.md
  gordon          → handoffs/gordon/Gordon-<key>.md
  gordon-split    → handoffs/gordon/Gordon-<key>-split.md
  harvey          → handoffs/harvey/Harvey-<key>.md
  harvey-session  → handoffs/harvey/Harvey-<key>-session.md
  signal          → handoffs/signal/Signal-<key>.md

Fields are written as **Key:** value lines. Special fields:
  - "_tables": dict of {section_name: [{col: val, ...}, ...]} → markdown tables
  - "_blocks": dict of {section_name: "content"} → fenced or plain text blocks
  - "_header": override the ## header line (default: derived from type)
  - "_delete_on_success": list of file paths to delete after write (e.g. notes file)
  - "_chain": list of prior handoff paths (e.g. ["alfred/Alfred-PAY-123.md", "lucius/Lucius-PAY-123.md"])
  - "_context": dict with keys: decisions, rejected, constraints, confidence_flags
  - "_conversation_context": dict for standalone agent operation. Standard keys:
      user_intent, decisions_and_reasoning, rejected_approaches,
      user_corrections, domain_knowledge, priority, whats_been_explained.
      Extra keys are also written. These carry the conversation context that
      would normally exist in the shared session but is lost in standalone mode.
  - "_raw": freeform string dumped as a **Raw Context:** section. Safety net for
      context that doesn't fit structured fields — the model dumps everything
      relevant from conversation here.
  - "_open_questions": list of {"question": str, "owner": str, "status": str}
      Unresolved questions that block the next phase. Rendered as a markdown table.
  - "_resume_instructions": string with explicit next-action text for the resuming agent.
      "Resolve X then do Y" rather than "Step 7".
  - "_conversation_export": path to /export transcript file. Cheap pointer to
      full conversational nuance that structured fields cannot capture.
  - "_ac_id": which acceptance criterion this handoff covers (e.g. "AC1").
      When present, appended to the filename: Damian-PAY6670-AC1.md.
      Also accepts a list for multi-AC handoffs: ["AC1", "AC2"].
  - "_depends_on": list of AC IDs this work depends on (e.g. ["AC1"])
  - "_agent_id": who wrote this handoff (e.g. "damian-a3f7"). Self-generated by agent.
  - "_parent": one-hop back link (e.g. "Alfred-PAY6670.md"). The handoff that routed here.
  - "_started_at": ISO timestamp when agent began work (not when handoff was saved).
  - "_patch": path to .patch file for Gordon commit queue.
  - "_queue_entry": which Oracle queue file spawned this work.
  - "_files_map": (deprecated — use flat `files_changed` field)

Output: one JSON document on stdout:
  {"ok": true, "status": "written", "type": ..., "ticket": ..., "path": ..., "self_evolution": ...}
Exit codes: 0 = written · 1 = usage error (bad JSON, missing type/ticket_key,
unknown type, required session fields missing, gherkin pointer detected)
"""
import os
import re
import subprocess
import sys
import json
from pathlib import Path
from datetime import date

from dupin_shared import (
    HANDOFF_PATHS,
    _DUPIN_PREFIX,
    _DUPIN_TYPES,
    build_ac_handoff_path,
    build_story_handoff_path,
)

from toolkit import Tool, UsageError

BASE_DIR = Path(__file__).resolve().parent.parent

HEADERS = {
    "oracle":         "## Oracle Handoff",
    "lucius":         "## Lucius Design Handoff",
    "alfred":         "## Alfred Handoff",
    "alfred-notes":   "## Alfred Session Progress",
    "damian":         "## Damian Handoff",
    "damian-case":    "# Case File: {key}",
    "bruce":          "## Bruce QA Handoff",
    "bruce-case":     "# Case File: {key}",
    "gordon":         "## Gordon Handoff",
    "gordon-split":   "## Gordon Scope-Split Handoff",
    "harvey":         "## Harvey Handoff",
    "harvey-session":  "## Harvey Session Handoff",
    "luke":            "## Luke Repo Intelligence Handoff",
    "blackgate":       "## Blackgate — Board Status",
    "signal":          "## Signal — Nightly Report",
    "skill-creator":   "# Skill Creator — {key}",
    "session":          "## Session Checkpoint",
    "dupin":              "## Dupin Handoff",
    "phase-state":        "## Dupin Phase State",
    "dup-implement":   "## Implementation Handoff — Dupin",
    "dup-commit":      "## Commit Handoff — Dupin",
    "dup-qa":          "## QA Handoff — Dupin",
    "dup-pr":          "## PR Handoff — Dupin",
}

# Standard field order shared by all pipeline handoff types.
# Skills may leave fields empty — the structure is the same everywhere.
# Skill-specific fields (in SKILL_FIELDS) come after the standard block.
# Any field in the JSON but not in either list goes at the end.
STANDARD_ORDER = [
    "Status", "Ticket", "Branch", "Repo Root", "Environment",
    "Mode", "Saved", "Route To",
    "Summary", "Current step", "Ticket Status",
]

# Skill-specific fields that appear after the standard block.
SKILL_FIELDS = {
    "oracle":         ["Diagnosed Intent", "Skills available"],
    "lucius":         ["Entry", "Escalation From", "Confidence", "Blueprint Path", "Delta HTML Path", "Delta Spec Path", "Epic Summary", "Target Directories"],
    "alfred":         ["Type", "Jira Updated", "Local ticket", "Impact", "Rollback", "PRD Path", "PRD Hash", "PRD Version", "Epic Phase", "Repos", "Lucius Story Map", "Blueprint Path", "Delta HTML"],
    "alfred-notes":   [],
    "damian":         ["Local ticket", "Partial", "A/C Selected (this session)", "Dev Style",
                       "TDD Classification", "TDD Red-Green Cycles", "Test Summary",
                       "Build Final", "Files Changed", "Components Created"],
    "bruce":          ["QA Result", "Test Types Run", "A/C Selected (this session)", "Test Summary", "QA Summary",
                       "Files Changed", "Failing Tests", "Gaps Addressed", "Gaps Deferred"],
    "bruce-case":     [],
    "gordon":         ["A/C Selected (this session)", "PR Comments", "Files Changed", "Review Findings", "Commit Hash"],
    "gordon-split":   ["Triggered by", "What was committed", "A/C to split out", "Gordon's notes"],
    "harvey":         ["PR", "A/C Selected (this session)", "Has Fix List",
                       "Fix List Details", "Skipped"],
    "harvey-session": ["PR", "Repo"],
    "luke":           ["Survey Mode", "Artifacts Written", "Anti-Patterns Found", "Staleness"],
    "dupin":              ["Phase", "Total Phases", "Stories", "Current Story", "ACs In Progress", "ACs Done", "ACs Merged", "Stories Merged to Epic"],
    "phase-state":        ["Phase", "Total Phases", "Stories", "Current Story", "ACs In Progress", "ACs Done", "ACs Merged", "Stories Merged to Epic"],
    "dup-implement":   ["Local ticket", "Partial", "A/C Selected (this session)", "Dev Style",
                           "TDD Classification", "TDD Red-Green Cycles", "Test Summary",
                           "Build Final", "Files Changed", "Components Created"],
    "dup-commit":      ["PR Comments", "Files Changed", "Review Findings", "Commit Hash"],
    "dup-qa":          ["QA Result", "Test Types Run", "A/C Selected (this session)",
                           "Test Summary", "QA Summary", "Files Changed",
                           "Failing Tests", "Gaps Addressed", "Gaps Deferred"],
    "dup-pr":          ["PR", "A/C Selected (this session)", "Has Fix List"],
}

# Non-pipeline types have their own field orders (no standard block).
STANDALONE_FIELD_ORDER = {
    "blackgate":      ["Board", "Date", "Total", "Summary"],
    "signal":         ["Date", "Status", "Summary", "Evo fixes"],
    "skill-creator":  ["Task", "Status", "Started", "Updated", "Saved", "Ticket"],
    "bruce-case":     ["Target", "Last updated"],
    "damian-case":    ["Target", "Last updated"],
    "session":        ["Topic", "Branch", "Repo Root", "Summary", "Whats Left", "Key Decisions", "Files Changed", "Date", "Status", "Route To", "Current step", "Ticket Status", "Version From", "Version To", "Tag", "Pushed"],
}

# Short aliases the model may use instead of canonical field names.
# Keys are lowercase; values are the exact canonical names from STANDARD_ORDER / SKILL_FIELDS.
ALIASES = {
    "ticket":           "Ticket",
    "status":           "Status",
    "branch":           "Branch",
    "repo":             "Repo Root",
    "repo_root":        "Repo Root",
    "env":              "Environment",
    "environment":      "Environment",
    "mode":             "Mode",
    "saved":            "Saved",
    "route":            "Route To",
    "route_to":         "Route To",
    "summary":          "Summary",
    "step":             "Current step",
    "current_step":     "Current step",
    "ticket_status":    "Ticket Status",
    # skill-specific
    "result":           "QA Result",
    "qa_result":        "QA Result",
    "test_types":       "Test Types Run",
    "dev_style":        "Dev Style",
    "partial":          "Partial",
    "local_ticket":     "Local ticket",
    "ac_selected":      "A/C Selected (this session)",
    "pr_comments":      "PR Comments",
    "pr":               "PR",
    "fix_list":         "Has Fix List",
    "has_fix_list":     "Has Fix List",
    "tdd_classification":    "TDD Classification",
    "tdd_red_green_cycles":  "TDD Red-Green Cycles",
    "test_summary":          "Test Summary",
    "build_final":           "Build Final",
    "files_changed":         "Files Changed",
    "files":                 "Files Changed",
    "review_findings":       "Review Findings",
    "commit_hash":           "Commit Hash",
    "qa_summary":            "QA Summary",
    "failing_tests":         "Failing Tests",
    "gaps_addressed":        "Gaps Addressed",
    "gaps_deferred":         "Gaps Deferred",
    "fix_list_details":      "Fix List Details",
    # dupin
    "phase":            "Phase",
    "total_phases":     "Total Phases",
    "acs_in_progress":  "ACs In Progress",
    "acs_done":         "ACs Done",
    "acs_merged":       "ACs Merged",
    "current_story":    "Current Story",
    "stories":          "Stories",
    "stories_merged_to_epic": "Stories Merged to Epic",
    # alfred
    "type":             "Type",
    "jira_updated":     "Jira Updated",
    "impact":           "Impact",
    "rollback":         "Rollback",
    "prd_path":         "PRD Path",
    "epic_phase":       "Epic Phase",
    "repos":            "Repos",
    "components_created":    "Components Created",
    # lucius
    "entry":                 "Entry",
    "escalation_from":       "Escalation From",
    "confidence":            "Confidence",
    "blueprint_path":        "Blueprint Path",
    "delta_html_path":       "Delta HTML Path",
    "delta_spec_path":       "Delta Spec Path",
    "epic_summary":          "Epic Summary",
    "target_directories":    "Target Directories",
    # luke
    "anti_patterns_found":   "Anti-Patterns Found",
}

# Top-level JSON keys that are control fields, not handoff fields.
# Never promoted into fields{}.
_RESERVED_TOP = {
    "type", "ticket_key", "base_dir", "self_evolution",
    "meta_efficiency", "fields", "repo_root",
}

# Fields auto-filled by the script. Model should never need to supply these.
_AUTO_FILL = {"Ticket", "Saved", "Environment", "Mode"}

# Fields that have real content — script cannot default them to N/A.
# All other declared fields default to N/A if absent.
_TRULY_REQUIRED = {
    "_base": ["Status", "Route To", "Summary", "Current step", "Ticket Status"],
    "damian":            ["A/C Selected (this session)", "Dev Style", "Branch",
                          "Repo Root", "Files Changed"],
    "gordon":            ["Branch", "Repo Root", "Files Changed", "Commit Hash",
                          "Review Findings"],
    "bruce":             ["QA Result", "Branch", "Repo Root", "QA Summary",
                          "Files Changed"],
    "harvey":            ["PR", "Has Fix List"],
    "dup-implement":  ["A/C Selected (this session)", "Dev Style", "Branch",
                          "Repo Root", "Files Changed", "Components Created"],
    "dup-commit":     ["Branch", "Repo Root", "Files Changed", "Commit Hash",
                          "Review Findings"],
    "dup-qa":         ["A/C Selected (this session)", "QA Result", "Branch",
                          "Repo Root", "QA Summary", "Files Changed", "Failing Tests"],
    "dup-pr":         ["A/C Selected (this session)", "PR"],
}


def _promote_flat_keys(args: dict) -> None:
    """Lift flat top-level keys into args['fields'], applying alias mapping.

    Flat keys don't overwrite keys already present in an explicit fields dict
    (old-format payloads win on conflict — backwards compatible).
    Underscore-prefixed and reserved keys are left in place for existing handlers.
    """
    fields = args.get("fields", {})
    for k, v in list(args.items()):
        if k in _RESERVED_TOP or k.startswith("_"):
            continue
        canonical = ALIASES.get(k.lower(), k)
        if canonical not in fields:
            fields[canonical] = v
    args["fields"] = fields


def _normalize_field_names(htype: str, fields: dict) -> None:
    """Rename mis-cased field keys to their canonical form in-place."""
    order = _get_field_order(htype)
    canonical_map = {f.lower(): f for f in order}
    for k in list(fields):
        lk = k.lower()
        if lk in canonical_map and canonical_map[lk] != k:
            fields[canonical_map[lk]] = fields.pop(k)


def _apply_field_defaults(htype: str, fields: dict, key: str) -> None:
    """Fill in auto-derived and N/A defaults for any declared field not supplied."""
    fields.setdefault("Ticket", key)
    # Normalize Ticket: strip AC suffix if model passed full ID (e.g. "LOC-0031-AC1" → "LOC-0031")
    ticket = fields.get("Ticket", "")
    _t_match = re.match(r"^(.+)-AC\d+$", ticket)
    if _t_match:
        fields["Ticket"] = _t_match.group(1)
    fields.setdefault("Saved", str(date.today()))
    fields.setdefault("Environment", "N/A")
    fields.setdefault("Mode", "N/A")
    for field_name in _get_field_order(htype):
        fields.setdefault(field_name, "N/A")


PIPELINE_NAMES = {
    "oracle": "Oracle", "alfred": "Alfred", "alfred-notes": "Alfred",
    "lucius": "Lucius", "damian": "Damian", "damian-case": "Damian",
    "gordon": "Gordon", "gordon-split": "Gordon", "bruce": "Bruce",
    "bruce-case": "Bruce", "harvey": "Harvey", "harvey-session": "Harvey",
    "luke": "Luke",
    "dupin": "Dupin", "phase-state": "Dupin",
    "dup-implement": "Dupin", "dup-commit": "Dupin",
    "dup-qa": "Dupin", "dup-pr": "Dupin",
}


def _get_field_order(htype: str) -> list:
    """Return the ordered field list for a handoff type."""
    if htype in STANDALONE_FIELD_ORDER:
        return STANDALONE_FIELD_ORDER[htype]
    return STANDARD_ORDER + SKILL_FIELDS.get(htype, [])


def _enforce_required_fields(htype: str, fields: dict) -> None:
    """Enforce only the fields the script cannot default — those carrying real session state.

    All other declared fields are filled with N/A by _apply_field_defaults before
    this runs. Only fields in _TRULY_REQUIRED need to be present and carry a real
    value: empty AND "N/A" both count as missing (N/A is a default, not state).
    Underscore-prefixed special fields are structural containers and remain optional.
    """
    required = list(_TRULY_REQUIRED.get("_base", []))
    required += _TRULY_REQUIRED.get(htype, [])
    # Standalone types have no standard block; skip base required for them.
    if htype in STANDALONE_FIELD_ORDER:
        required = _TRULY_REQUIRED.get(htype, [])
    # Repo-intelligence types have no ticket; remove ticket-specific base requirements.
    if htype in {"luke"}:
        required = [f for f in required if f != "Ticket Status"]
    # "Route To" and "Ticket Status" are legitimately N/A (no next skill; local
    # tickets without Jira) — every other truly-required field must carry real state.
    na_exempt = {"Route To", "Ticket Status"}
    def _is_missing(v):
        return not v or str(v).strip().upper() == "N/A"
    missing = [f for f in required
               if f not in na_exempt and _is_missing(fields.get(f))]
    if missing:
        raise UsageError(
            f"'{htype}' handoff is missing required session fields: "
            + ", ".join(f"missing: {f}" for f in missing),
            "these fields cannot be defaulted — they carry real session state; add them to the JSON payload",
        )


# Phrases that indicate the model pointed at Jira instead of writing the actual
# Gherkin inline. Bruce (and any other downstream reader) must get the AC text
# in the handoff itself — a pointer means they have to go fetch the ticket.
_AC_POINTER_PATTERNS = [
    "see the jira ticket", "see jira", "in the jira ticket", "in the ticket description",
    "refer to jira", "refer to the ticket", "full gherkin scenarios are in the jira ticket",
    "expand blocks", "check jira for", "jira has the full",
]


def _enforce_alfred_gherkin(fields: dict) -> None:
    """Alfred must hand Bruce/Damian the actual Gherkin, not a pointer back to Jira.

    Only applies when routing to bruce or damian — the two skills that
    implement/test directly against the AC. Routes to lucius (pre-design,
    ACs not finalized) or dupin (epic-level story breakout, per-story
    handoffs carry their own AC) are exempt.

    Checks the '_blocks.Acceptance Criteria' content (or the flat 'Acceptance
    Criteria' field, since models sometimes put it top-level) for a real
    Given/When/Then body. A handoff that only summarizes AC titles and tells
    the reader to go look at Jira defeats the purpose of the handoff.
    """
    route_to = str(fields.get("Route To", "")).strip().lower()
    if route_to not in {"bruce", "damian"}:
        return

    blocks = fields.get("_blocks") or {}
    ac_text = blocks.get("Acceptance Criteria") or fields.get("Acceptance Criteria") or ""
    if not isinstance(ac_text, str):
        ac_text = str(ac_text)
    lower = ac_text.lower()

    if not ac_text.strip():
        raise UsageError(
            "'alfred' handoff is missing '_blocks.Acceptance Criteria' — the full "
            "refined Gherkin must be written into the handoff, not left for the reader to fetch from Jira",
            "write the full Given/When/Then scenarios into _blocks['Acceptance Criteria']",
        )

    for pattern in _AC_POINTER_PATTERNS:
        if pattern in lower:
            raise UsageError(
                f"'alfred' handoff's Acceptance Criteria contains a Jira pointer phrase "
                f"('{pattern}') instead of the actual Gherkin",
                "write the full Given/When/Then scenarios inline in the handoff",
            )

    if "given" not in lower or "when" not in lower or "then" not in lower:
        raise UsageError(
            "'alfred' handoff's Acceptance Criteria has no Given/When/Then content",
            "write the full refined Gherkin scenarios into the handoff so Bruce/Damian don't have to open the Jira ticket",
        )


def _make_table(rows: list[dict]) -> str:
    """Build a markdown table from a list of row dicts."""
    if not rows:
        return ""
    cols = list(rows[0].keys())
    lines = []
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("| " + " | ".join("---" for _ in cols) + " |")
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(c, "")) for c in cols) + " |")
    return "\n".join(lines)




def build_handoff(htype: str, key: str, fields: dict) -> str:
    """Build the markdown content for a handoff file."""
    header = fields.pop("_header", HEADERS.get(htype, f"## {htype} Handoff"))
    header = header.replace("{key}", key)
    tables = fields.pop("_tables", {})
    blocks = fields.pop("_blocks", {})
    fields.pop("_delete_on_success", None)  # handled by caller
    chain = fields.pop("_chain", [])
    context = fields.pop("_context", {})
    conversation_context = fields.pop("_conversation_context", {})
    raw_context = fields.pop("_raw", "")
    ac_id = fields.pop("_ac_id", None)
    depends_on = fields.pop("_depends_on", [])
    fields.pop("_files_map", None)  # deprecated — flat files_changed field used instead
    agent_id = fields.pop("_agent_id", None)
    parent = fields.pop("_parent", None)
    started_at = fields.pop("_started_at", None)
    patch_path = fields.pop("_patch", None)
    queue_entry = fields.pop("_queue_entry", None)
    open_questions = fields.pop("_open_questions", [])
    resume_instructions = fields.pop("_resume_instructions", "")
    conversation_export = fields.pop("_conversation_export", "")

    lines = [header]

    # Pipeline position banner — receiving skill sees sender + intent first
    sender = PIPELINE_NAMES.get(htype)
    route_to = fields.get("Route To", "")
    if sender and htype not in STANDALONE_FIELD_ORDER:
        if route_to:
            lines.append(f"**Gotham Pipeline** · {sender} → {route_to}")
        else:
            lines.append(f"**Gotham Pipeline** · {sender}")

    # Auto-insert grep-friendly completion stamp when Status is a completion
    # value. 'complete' is canonical, but models may write 'done'/'passed'/
    # 'success' — normalize all of them so downstream scanners (find_handoff,
    # validate_handoff_chain) never treat a finished handoff as missing.
    COMPLETE_STATUSES = {"complete", "done", "passed", "pass", "success"}
    if fields.get("Status", "").lower() in COMPLETE_STATUSES:
        lines.append("status: complete")

    # Ordered fields first
    order = _get_field_order(htype)
    written = set()

    for field_name in order:
        if field_name in fields:
            lines.append(f"**{field_name}:** {fields[field_name]}")
            written.add(field_name)

    # Remaining fields (not in order list, not special)
    for field_name, value in fields.items():
        if field_name not in written:
            lines.append(f"**{field_name}:** {value}")

    # V2 fields — agent identity, chain, context, AC tracking, file map
    if agent_id:
        lines.append(f"**Agent:** {agent_id}")
    if parent:
        lines.append(f"**Parent:** {parent}")
    if started_at:
        lines.append(f"**Started At:** {started_at}")
    if patch_path:
        lines.append(f"**Patch:** {patch_path}")
    if queue_entry:
        lines.append(f"**Queue Entry:** {queue_entry}")
    if ac_id:
        if isinstance(ac_id, list):
            lines.append(f"**AC:** {', '.join(ac_id)}")
        else:
            lines.append(f"**AC:** {ac_id}")
    if depends_on:
        lines.append(f"**Depends On:** {', '.join(depends_on)}")
    if chain:
        lines.append("")
        lines.append("**Chain:**")
        for link in chain:
            lines.append(f"- `{link}`")
    if context:
        lines.append("")
        lines.append("**Context:**")
        for ctx_key, ctx_val in context.items():
            if isinstance(ctx_val, list):
                lines.append(f"- **{ctx_key}:** {'; '.join(ctx_val)}")
            elif isinstance(ctx_val, dict):
                items = [f"{k}: {v}" for k, v in ctx_val.items()]
                lines.append(f"- **{ctx_key}:** {'; '.join(items)}")
            else:
                lines.append(f"- **{ctx_key}:** {ctx_val}")
    # Conversation context — structured context for standalone agent operation
    CONV_CTX_FIELDS = [
        "user_intent", "decisions_and_reasoning", "rejected_approaches",
        "user_decisions", "domain_knowledge", "priority", "whats_been_explained",
    ]
    CONV_CTX_LABELS = {
        "user_intent": "User intent",
        "decisions_and_reasoning": "Decisions and reasoning",
        "rejected_approaches": "Rejected approaches",
        "user_decisions": "User decisions",
        "domain_knowledge": "Domain knowledge",
        "priority": "Priority",
        "whats_been_explained": "What's been explained",
    }
    if conversation_context:
        lines.append("")
        lines.append("**Conversation Context:**")
        for field in CONV_CTX_FIELDS:
            val = conversation_context.get(field)
            if val:
                lines.append(f"- **{CONV_CTX_LABELS[field]}:** {val}")
        # Any extra keys not in the standard set
        for k, v in conversation_context.items():
            if k not in CONV_CTX_FIELDS and v:
                lines.append(f"- **{k}:** {v}")

    # Raw context dump — freeform content for standalone agents
    if raw_context:
        lines.append("")
        lines.append("**Raw Context:**")
        lines.append(raw_context)

    # Open questions — structured blockers for next phase
    if open_questions:
        lines.append("")
        lines.append("**Open Questions:**")
        lines.append(_make_table(open_questions))

    # Resume instructions — explicit next-action for resuming agent
    if resume_instructions:
        lines.append("")
        lines.append(f"**Resume Instructions:** {resume_instructions}")

    # Conversation export — pointer to full transcript
    if conversation_export:
        lines.append(f"**Conversation Export:** {conversation_export}")

    # Tables
    for section_name, rows in tables.items():
        lines.append("")
        lines.append(f"**{section_name}:**")
        lines.append(_make_table(rows))

    # Text blocks
    for section_name, content in blocks.items():
        lines.append("")
        lines.append(f"**{section_name}:**")
        if isinstance(content, list):
            if content and all(isinstance(r, dict) for r in content):
                lines.append(_make_table(content))
            else:
                for item in content:
                    lines.append(str(item))
        elif isinstance(content, dict):
            for k, v in content.items():
                lines.append(f"- **{k}:** {v}")
        else:
            lines.append(content)

    return "\n".join(lines) + "\n"


def _strip_surrogates(obj):
    """Recursively strip lone surrogate characters from all string values."""
    if isinstance(obj, str):
        return obj.encode("utf-8", errors="replace").decode("utf-8")
    if isinstance(obj, dict):
        return {k: _strip_surrogates(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_strip_surrogates(v) for v in obj]
    return obj


def handle(v):
    raw = v["--json"]
    if raw == "-":
        raw = sys.stdin.read().strip()
    if not raw:
        raise UsageError(
            "empty JSON payload",
            "pipe the payload via stdin: $UB make-handoff --json - <<'HANDOFF' ... HANDOFF",
        )
    try:
        args = json.loads(raw)
    except json.JSONDecodeError as e:
        raise UsageError(f"invalid JSON payload: {e}", "fix the JSON and re-run")
    if not isinstance(args, dict):
        raise UsageError(
            "JSON payload must be an object",
            "use {\"type\": ..., \"ticket_key\": ..., \"fields\": {...}}",
        )

    base = Path(args.get("base_dir") or v["--base"])
    htype = args.get("type")
    key = args.get("ticket_key")
    if not htype:
        raise UsageError("'type' is required in the JSON payload", "add \"type\": \"<handoff type>\"")
    if not key:
        raise UsageError("'ticket_key' is required in the JSON payload", "add \"ticket_key\": \"<KEY>\"")

    # --- Flat interface: lift top-level keys into fields, apply aliases + defaults ---
    _promote_flat_keys(args)
    fields = args.get("fields", {})

    # Rescue special keys placed at top level instead of inside fields.
    # Models frequently put _blocks, _tables, _context etc. as siblings of
    # "type"/"ticket_key" rather than nested in "fields". Merge them in so
    # build_handoff sees them regardless of where the model placed them.
    _SPECIAL = {
        "_blocks", "_tables", "_header", "_delete_on_success", "_chain",
        "_context", "_conversation_context", "_raw", "_ac_id", "_depends_on",
        "_files_map", "_agent_id", "_parent", "_started_at",
        "_patch", "_queue_entry", "_open_questions", "_resume_instructions",
        "_conversation_export",
    }
    for sk in _SPECIAL:
        if sk in args and sk not in fields:
            fields[sk] = args[sk]

    if htype not in HANDOFF_PATHS:
        raise UsageError(
            f"unknown handoff type: {htype}. Valid: {', '.join(HANDOFF_PATHS.keys())}",
            "use one of the valid handoff types listed in the error",
        )

    # Dupin epic/phase state is per-EPIC — never per-AC. An AC-suffixed key here
    # produced top-level handoffs/dupin/<STORY>-AC<n>.md files the scanner doesn't
    # read; per-AC state belongs in the dup-* stage files.
    if htype in ("dupin", "phase-state") and re.search(r"-AC\d+$", key):
        raise UsageError(
            f"'{htype}' is epic/phase state — key {key!r} has an AC suffix",
            "use the dup-* stage types for stage handoffs (they write handoffs/dupin/<STORY>/<stage>-<STORY>.md)",
        )

    _normalize_field_names(htype, fields)
    _apply_field_defaults(htype, fields, key)
    _enforce_required_fields(htype, fields)
    if htype == "alfred":
        _enforce_alfred_gherkin(fields)

    folder, filename_template = HANDOFF_PATHS[htype]
    out_dir = base / folder
    out_dir.mkdir(parents=True, exist_ok=True)

    se_status = "skipped"

    if htype == "session":
        completed_dir = out_dir / "completed"
        completed_dir.mkdir(parents=True, exist_ok=True)
        for old in out_dir.glob("Session-*.md"):
            old.replace(completed_dir / old.name)

    if htype in _DUPIN_TYPES:
        # ac_selected is aliased to "A/C Selected (this session)" by _promote_flat_keys
        ac_selected = fields.get("A/C Selected (this session)", "")
        # Strip AC suffix from key if present (e.g. "LOC-0035-AC2" → "LOC-0035")
        _key_strip = re.match(r"^(.+)-AC\d+$", key)
        story_key = _key_strip.group(1) if _key_strip else key
        if re.search(r"-AC\d+$", story_key):
            # Doubled per-AC dir (handoffs/dupin/<STORY>-AC<n>/<stage>-<STORY>-AC<n>-AC<n>.md)
            # is scanner-invisible. The story key itself must not carry an AC suffix.
            raise UsageError(
                f"story key {story_key!r} still carries an AC suffix",
                "pass ticket_key as <STORY> or <STORY>/AC<n> so the file lands in handoffs/dupin/<STORY>/",
            )
        # Extract unit from ac_selected (story key, legacy per-AC key, or "pr-<STORY>" for PRs)
        if htype == "dup-pr" and ac_selected.startswith("pr-"):
            ac_id_for_path = ac_selected
        elif "/" in key:
            _, ac_id_for_path = key.rsplit("/", 1)
        else:
            _ac_extract = re.search(r"(AC\d+)", ac_selected)
            ac_id_for_path = _ac_extract.group(1) if _ac_extract else ac_selected
        # build_ac_handoff_path appends "handoffs/dupin/<story>" itself, so the
        # base must be BASE_DIR (~/.claude) — passing out_dir.parent produced a
        # nested handoffs/handoffs/dupin/ tree the scanner never reads.
        # Story-level dispatch (dupin plan §3.3): ac_selected carries a bare
        # story key (no AC suffix) → deterministic story handoff path
        # {stage}-{STORY}.md. Everything else keeps the legacy per-AC path.
        if htype != "dup-pr" and re.fullmatch(r"[A-Z][A-Z0-9]*-\d{3,4}", ac_id_for_path):
            out_path = build_story_handoff_path(base, htype, story_key)
        else:
            out_path = build_ac_handoff_path(base, htype, story_key, ac_id_for_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fields = _strip_surrogates(fields)
        content = build_handoff(htype, key, dict(fields))
        out_path.write_text(content, encoding="utf-8")
        _post_write(base, htype, key, str(out_path),
                    agent_id=fields.get("_agent_id"))
        return {
            "status": "written",
            "type": htype,
            "ticket": key,
            "path": str(out_path),
            "self_evolution": se_status,
        }

    base_filename = filename_template.replace("{key}", key).replace("{ac_id}", key.split("/")[-1] if "/" in key else key)

    out_path = out_dir / base_filename

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fields = _strip_surrogates(fields)
    content = build_handoff(htype, key, dict(fields))  # copy to avoid mutation
    out_path.write_text(content, encoding="utf-8")

    # Delete files on success (e.g. notes file superseded by full handoff)
    # Guard: never delete the file we just wrote
    for del_path in args.get("fields", {}).get("_delete_on_success", []):
        p = Path(del_path).resolve()
        if p == out_path.resolve():
            continue
        if p.exists():
            p.unlink()

    # Audit post-write
    _post_write(base, htype, key, str(out_path))

    # Self-evolution check — runs inline after handoff write
    se_items = args.get("self_evolution")
    if se_items is not None:
        se_status = _run_self_evolution(se_items)

    return {
        "status": "written",
        "type": htype,
        "ticket": key,
        "path": str(out_path),
        "self_evolution": se_status,
    }


TOOL = Tool(
    name="make-handoff",
    version="1.0",
    summary="Write a pipeline handoff markdown file from a JSON payload (all skill types, GPTS).",
    flags={
        "--json": {"required": True, "type": "str",
                   "description": "JSON payload blob, or '-' to read the payload from stdin (heredoc)."},
    },
    exit_codes={
        "0": "handoff written — payload: type, ticket, path, self_evolution (cleared|pending|skipped)",
        "1": "usage error — bad JSON, missing type/ticket_key, unknown type, required session fields missing, or gherkin pointer detected",
    },
    examples=[
        "$UB make-handoff --json - <<'HANDOFF'\n"
        "{\"type\": \"bruce\", \"ticket_key\": \"LOC-0076\", \"fields\": {\"Status\": \"pass\"}}\n"
        "HANDOFF",
    ],
    idempotent="Overwrites the target handoff file; re-running with the same payload is safe.",
    base_default=BASE_DIR,
)


_SUBAGENT_ID_RE = re.compile(r"^dup-(implement|commit|qa|pr)-[0-9a-f]{4,}$")


def _post_write(base_dir, htype, key, out_path, agent_id=None):
    """Audit log always (background append to audits/<ticket>/audit.md)."""
    # dup-* types must not collapse to "dup" — keep the full type as the
    # default audit role so audit-log query can filter by stage.
    base_type = htype if htype in _DUPIN_TYPES else htype.split("-")[0]
    tools_dir = Path(__file__).resolve().parent
    devnull = subprocess.DEVNULL

    # --- Audit: always write to audits/<ticket>/ ---
    # audit-log.py is GPTS: flags-only CLI (--op append --ticket K --role R
    # --type T --text "..."). The old positional (command, ticket) form is gone.
    audit_script = tools_dir / "audit-log.py"
    if audit_script.exists():
        subprocess.Popen(
            [sys.executable, str(audit_script),
             "--op", "append", "--ticket", key, "--role", base_type,
             "--type", "context",
             "--text", f"Handoff written: {htype} for {key}"],
            stdout=devnull, stderr=devnull,
        )
        # --- Dupin subagent stages: machine-readable RESULT line so
        #     `audit-log query` has a per-stage completion record. Role is the
        #     subagent ID when it matches the allowlist scheme, else the type.
        if htype in _DUPIN_TYPES:
            role = agent_id if (agent_id and _SUBAGENT_ID_RE.fullmatch(agent_id)) else htype
            stage = _DUPIN_PREFIX.get(htype, htype)
            subprocess.Popen(
                [sys.executable, str(audit_script),
                 "--op", "append", "--ticket", key, "--role", role,
                 "--type", "progress",
                 "--text", f"RESULT: {stage} stage handoff for {key} — {out_path}"],
                stdout=devnull, stderr=devnull,
            )


def _run_self_evolution(corrections):
    """Triage user corrections noted during the session.

    Empty list = no corrections = routing proceeds.
    Non-empty list = print corrections for user triage before routing.
    """
    # Import shared state module from hooks directory
    hooks_dir = os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "hooks")
    )
    sys.path.insert(0, hooks_dir)
    from compliance_state import locked_state

    state_file = os.path.join(
        os.path.expanduser("~"), ".claude", "logs", "compliance",
        "self-evolution-state.json"
    )

    with locked_state(state_file) as data:
        if not corrections:
            data["status"] = "cleared"
            data["corrections"] = []
            print("Self-evolution check: no corrections noted. Routing cleared.", file=sys.stderr)
            return "cleared"
        else:
            data["status"] = "pending"
            data["corrections"] = corrections
            data["resolved"] = False
            print("=" * 60, file=sys.stderr)
            print("SELF-EVOLUTION — User corrections noted this session:", file=sys.stderr)
            print("=" * 60, file=sys.stderr)
            for i, c in enumerate(corrections, 1):
                print(f"  {i}. {c}", file=sys.stderr)
            print(file=sys.stderr)
            print("Present these to the user:", file=sys.stderr)
            print("  (a) Fix now — invoke /skill-creator", file=sys.stderr)
            print("  (b) Defer  — add to pipeline-notes.md", file=sys.stderr)
            return "pending"


if __name__ == "__main__":
    TOOL.run(handle)
